name: Build Master
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    strategy:
      max-parallel: 2
      matrix:
        java:
          - '8'
          - '11'
          - '17'
        os:
          - ubuntu-latest
          - macos-latest
        exclude:
          - os: macos-latest
            java: '8'
          - os: macos-latest
            java: '11'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Build
        run: |
          ./gradlew -S -Pskip.signing=true assemble
          ./gradlew -S -Pskip.signing=true check
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Assemble
        shell: cmd
        run: |
          gradlew.bat -i assemble
      - name: Check
        shell: cmd
        run: |
          gradlew.bat -S -Pskip.signing=true assemble
          gradlew.bat -S -Pskip.signing=true check


